apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cve-generator.fullname" . }}
  namespace: cve-generator
  labels:
    {{- include "cve-generator.labels" . | nindent 4 }}
    app: cve-generator
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "cve-generator.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            app: cve-generator
        spec:
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - cve-generator
                    topologyKey: "topology.kubernetes.io/zone"
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: data
                  mountPath: /mnt/data
          imagePullSecrets: 
            {{- if .Values.image.imagePullSecrets }}
            - name: {{ .Values.image.imagePullSecrets }}
            {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy | default "OnFailure" }}
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: "{{ .Values.pvc.name }}"
