apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cve-generator.fullname" . }}-immediate-run
  namespace: cve-generator
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- include "cve-generator.labels" . | nindent 4 }}
    app: cve-generator
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cve-generator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: cve-generator
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cve-generator
                topologyKey: "topology.kubernetes.io/zone"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /mnt/data
      imagePullSecrets: 
        {{- if .Values.image.imagePullSecrets }}
        - name: {{ .Values.image.imagePullSecrets }}
        {{- end }}
      restartPolicy: {{ .Values.cronjob.restartPolicy | default "OnFailure" }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Values.pvc.name }}"