apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.pvc.name }}"
  labels:
    {{- include "cve-generator.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: {{ .Values.pvc.storageClass | default "gp2" }}
